<?php
/**
 * Created by PhpStorm.
 * User: insxcloud
 * Date: 15/06/2017
 * Time: 11:09
 */

namespace Plan\Controller;


use Plan\Service\Plan as PlanService;
use Zend\Mvc\Controller\AbstractRestfulController;

class PlanController extends AbstractRestfulController
{
    protected $service;

    public function __construct(PlanService $service)
    {
        $this->service = $service;
    }

    public function getList()
    {
        return parent::getList(); // TODO: Change the autogenerated stub
    }

    public function get($id)
    {
        return parent::get($id); // TODO: Change the autogenerated stub
    }

    public function create($data)
    {
        dump ($data);
        $this->service->create($data);

        return parent::create($data); // TODO: Change the autogenerated stub
    }

    public function update($id, $data)
    {
        return parent::update($id, $data); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        $this->service->delete($id);


        return parent::delete($id); // TODO: Change the autogenerated stub
    }

}